name: Release Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: CI= yarn build

      - name: Publish
        run: echo "//registry.npmjs.org/:_authToken=${NPM_SECRETS}" > ~/.npmrc && yarn publish
        env:
          NPM_SECRETS: ${{secrets.NPM_SECRETS}}
